---
ID: "d43274f4-b8ec-43c5-b9bc-4e66c80aa304"
Parent: "d962a41c-0041-48be-a81a-9753fc7ccef1"
Template: "d962a41c-0041-48be-a81a-9753fc7ccef1"
Path: /sitecore/templates/Project/Hackathon/Sandbox/Team/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200229T220335Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
