---
ID: "94945177-8d23-467e-b2bb-6b0148771357"
Parent: "39de99d4-bc96-43bc-8baa-3ec379a86a23"
Template: "39de99d4-bc96-43bc-8baa-3ec379a86a23"
Path: /sitecore/templates/Project/Hackathon/Sandbox/Settings/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200229T113830Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\ajoshi
