---
ID: "ee77b4c9-56c6-4926-b754-3eabda51c536"
Parent: "4ba40cb5-5f2a-4bdd-bd6a-561f539c9c57"
Template: "4ba40cb5-5f2a-4bdd-bd6a-561f539c9c57"
Path: /sitecore/templates/Project/Hackathon/Sandbox/Page Designs/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: |
    {FA5AF3B7-CAE9-4900-B34D-55D6CACE0B24}
    {EDF70823-D59C-4B75-83BC-D30A08211BA8}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200229T113829Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\ajoshi
